type Query {
  hub(id: String): Hub
  users: Users
}

type Mutation {
  createHub(name: String!): Hub!
  createItem(id: String!, url: URL!): Item!
}

scalar URL

type Hub {
  id: String!
  creator: String!
  name: String!
  url: URL!
  items: [Item!]!
}

type Item {
  id: String!
  url: URL!
  origin: URL!
}

type Users {
  me: User
  user(id: String): User
}

type User {
  id: String!
  name: String!
  hubs: [Hub!]!
}
