directive @auth(requires: Role = USER) on OBJECT | FIELD_DEFINITION

enum Role {
  OWNER
  ADMIN
  USER
}

type User {
  analytics: Analytics!
  id: String!
  name: String!
  hubs: [Hub!]!
}

type Analytics {
  daily: [AnalyticsSampleData!]!
  retention: [AnalyticsSampleData!]!
  total: [AnalyticsSampleData!]!
}

type AnalyticsSampleData {
  value: Int!
  date: DateTime!
}

scalar DateTime

scalar URL

type Query {
  hub(id: String): Hub
  users: Users
}

type Mutation {
  createHub(name: String!): Hub!
  createItem(id: String!, url: URL!): Item!
}

type Hub {
  id: String!
  creator: String!
  name: String!
  url: URL!
  items: [Item!]!
}

type Item {
  id: String!
  url: URL!
  origin: URL!
}

type Users {
  me: User
  user(id: String): User
}
